# Generated by Django 5.0.2 on 2024-03-24 11:11

import app.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator(message='please enter correct email')])),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(5, message='name shoulb be 5 character'), django.core.validators.RegexValidator(message='name shouble character not number or symbol', regex='^[^\\W\\d_]+$')])),
                ('phone', models.CharField(max_length=10, validators=[app.models.name_validator])),
                ('dob', models.DateField()),
                ('city', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
