# Generated by Django 5.0.2 on 2024-03-24 11:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_user_name_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='number should be 10 digit', regex='^[0-9]{10}$')]),
        ),
    ]
