# Generated by Django 5.0.2 on 2024-03-24 11:25

import app.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_user_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(5, message='name shoulb be 5 character'), app.models.name_validator]),
        ),
    ]
