# Generated by Django 5.0.2 on 2024-03-24 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_user_name_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('superuser', 'SuperUser'), ('student', 'Student')], default='student', max_length=20),
            preserve_default=False,
        ),
    ]
