# Generated by Django 5.0.2 on 2024-03-24 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_course_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='name',
            new_name='course_name',
        ),
    ]
